name: Two-Bit History
url: https://twobithistory.org
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      comments: true
plugins:
  - jekyll-feed
