name: Two-Bit History
title: Two-Bit History
url: https://twobithistory.org
excerpt_separator: <!--more-->
paginate: 10
defaults:
  -
    scope:
      path: ""
    values:
      title: 'Two-Bit History'
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-paginate
